name: Run Webscraper

on:
  schedule:
    - cron: "17 8 * * 6"  # Run on Saturdays at 08:00 AM in Sao Paulo timezone

env:
  TZ: America/Sao_Paulo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python vagas.py

      - name: Commit changes
        run: |
          git config --global user.name "Joao Pedro"
          git config --global user.email "joaoaffonso@id.uff.br"
          git add *.png *.csv
          git commit -m "Update data"
          git push
